blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Questions or ideas?
    url: https://github.com/airjp73/remix-validated-form/discussions
    about: Ask long-form questions and discuss ideas.
  - name: ðŸ’¬ Remix Discord / Community Chat
    url: https://rmx.as/discord
    about: Interact with other people using Remix ðŸ“€